[package]
name = "mair"
version = "0.1.0"
authors = ["uHOOCCOOHu <uHOOCCOOHu@users.noreply.github.com>"]

[lib]
name = "mair"
path = "src/mair/lib.rs"

[[bin]]
name = "mair"
path = "src/bin/main.rs"
doc = false

[features]
default = []
